### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by therus000** [C2-Labs/k8s-security-elasticsearch#2]
i got Kibana server is not ready yet when i deploy all

**Comment by therus000** [comment]
on es-client i got crashloop ElasticsearchSecurityException[failed to load SSL configuration [xpack.security.http.ssl]]; nested: ElasticsearchException[failed to initialize SSL TrustManager]; nested: CertificateParsingException[Empty issuer DN not allowed in X509Certificates];

**Comment by ShannonHung** [comment]
The problem is cert-manager
you need to add spec.subject and spec.commonName like below: 

```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: logging
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-http-tls
  namespace: logging
spec:
  isCA: true
  dnsNames:
    - es-cluster-svc
    - es-cluster-svc.logging.svc
    - es-cluster-svc.logging.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: es-http-tls
  commonName: quickstart
  subject:
    organizations:
      - quickstart
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: logging
spec:
  isCA: true
  duration: 2h # 90d
  renewBefore: 1h # 7d
  dnsNames:
    - localhost
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kibana-tls
  commonName: quickstart
  subject:
    organizations:
      - quickstart
```
